routes/web.php
<?php

use App\Http\Controllers\AdminHomeController;
use App\Http\Controllers\AssignUserController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin']], function () {
    // dashboard routes
    Route::resource('/', AdminHomeController::class)->name('*', 'dashboard');

    // projects routes
    Route::resource('/projects', ProjectController::class)->name('*', 'projects');

    // projects category routes
    Route::resource('/categories', CategoryController::class)->name('*', 'categories');

    // users routes
    Route::resource('/users', UserController::class)->name('*', 'users');

    // profile routes
    Route::get('/profile', function () {return view('welcome');})->name('Profile');
});

Route::group(['prefix' => '', 'middleware' => ['auth', 'user']], function () {

    // Route::get('/', function () {
    //     return view('user.dashboard');
    // })->middleware(['auth'])->name('dashboard');

    // dashboard routes
    Route::resource('/', HomeController::class)->name('*', 'dashboard');

    // user routes
    Route::resource('/user', UserController::class)->name('*', 'user');

    // projects routes
    Route::resource('/my/project', ProjectController::class)->name('*', 'project');

    // projects category routes
    Route::resource('/assign', AssignUserController::class)->middleware(['auth'])->name('*', 'assign');
});

require __DIR__ . '/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/admin/category_form.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Settings') }}
        </h2>
    </x-slot>

    @if($errors->any())
        @foreach($errors->all() as $error)
        <div class="border-t-4 border-teal-500 rounded-b px-4 py-3 shadow-md bg-red-500 text-white absolute" role="alert">
            <div class="flex items-center">
                <div class="py-1">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-16 w-16" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                </div>
                <div>
                    <p class="font-bold">Error</p>
                    <p class="text-sm">{{$error}}</p>
                </div>
            </div>
        </div>
        @endforeach
    @endif



    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="bg-blue-500 overflow-hidden shadow-sm sm:rounded-lg">
                    <div class="pt-8 pb-4" style="height: 200px !important;">
                    <h4 class="bg-white border rounded mt-2 p-2 ml-2">All Categories</h4>
                        <div class="pr-2" style="height: 200px !important;">
                            <ul class="row" style="height: 200px !important;">
                                @foreach($all_categories as $category)
                                    <div class="col-lg-6">
                                        <li class="box__user graph">
                                            <div class="box__description">
                                                <a href="{{route('categories.edit', $category->id)}}" class="">{{$category->title}}</a>
                                                <p class="overflow-ellipsis w-full font-thin capitalize text-gray-200 text-xs">{{$category->desc}}</p>
                                            </div>
                                            <div class="box__image">
                                                <a href="{{route('categories.edit', $category->id)}}" class="">
                                                    <svg xmlns="http://www.w3.org/2000/svg" class="h- w-25" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                                                    </svg>
                                                </a>
                                                <a onclick="return confirm('etes-vous sur de vouloir supprimer?')" href="{{route('categories.destroy', $category->id)}}" class="text-danger">
                                                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-25" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M6 18L18 6M6 6l12 12" />
                                                    </svg>
                                                </a>
                                            </div>
                                        </li>
                                    </div>
                                @endforeach
                            </ul>
                        </div>

                    </div>
                </div>
            </div>

            <div class="col-lg-4">
                <div class="bg-white border rounded m-2 p-4">

                    @if(Session::has('success'))
                        <div class="alert alert-success">
                            {{session('success')}}
                        </div>
                    @endif

                    <div class="border-bottom">
                        <p>Create new category</p>
                    </div>
                    @if(request()->routeIs('categories.index'))
                        <form action="{{route('categories.store')}}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('post')
                            <div class="form-input">
                                <label class="">Title</label>
                                <input class="form-control" type="text" placeholder="Title..." name="title" />
                            </div>

                            <div class="form-input">
                                <label class="">Description</label>
                                <textarea class="form-control resize-none" name="desc" cols="30" rows="4" placeholder="Description..."></textarea>
                            </div>

                            <div class="mt-2 border-bottom mb-2">
                                <label for="file-upload" class="d-flex justify-content-between">
                                    <!-- <svg class="mx-auto h-12 w-12 text-gray-400 w-25" stroke="currentColor" fill="none" viewBox="0 0 48 48" aria-hidden="true">
                                        <path d="M28 8H12a4 4 0 00-4 4v20m32-12v8m0 0v8a4 4 0 01-4 4H12a4 4 0 01-4-4v-4m32-4l-3.172-3.172a4 4 0 00-5.656 0L28 28M8 32l9.172-9.172a4 4 0 015.656 0L28 28m0 0l4 4m4-24h8m-4-4v8m-12 4h.02" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                                    </svg> -->
                                    <span class="btn btn-sm btn-primary">Upload image</span>
                                    <input id="file-upload" name="post_img" type="file" class="sr-only" accept="image/jpeg, image/png">
                                </label>
                            </div>

                            <div class="">
                                <button class="btn btn-sm btn-primary" type="submit">Save</button>
                                <a href="{{route('categories.index')}}" class="btn btn-sm btn-danger" type="reset">Clear</a>
                            </div>
                        </form>
                            @else
                                <form action="{{route('categories.update', $edit_category->id)}}" method="POST" enctype="multipart/form-data">
                                    @csrf
                                    @method('put')
                                    <div class="form-input">
                                        <label class="block text-sm font-medium text-gray-700">Title</label>
                                        <input class="form-control" type="text" placeholder="Title..." name="title" value="{{$edit_category->title}}" />
                                    </div>

                                    <div class="mb-2">
                                        <label class="block text-sm font-medium text-gray-700">Description</label>
                                        <textarea class="form-control resize-none" name="desc" cols="30" rows="4" placeholder="Description...">{{$edit_category->desc}}</textarea>
                                    </div>

                                    <div class="mb-2 border-bottom">
                                        <div class="flex text-sm text-gray-600">
                                            <label for="file-upload" class="relative cursor-pointer bg-white rounded-md font-medium text-indigo-600 hover:text-indigo-500 focus-within:outline-none focus-within:ring-2 focus-within:ring-offset-2 focus-within:ring-indigo-500">
                                                <span class="btn btn-sm btn-primary">Upload</span>
                                                <input id="file-upload" name="post_img" type="file" class="sr-only" accept="image/jpeg, image/png">
                                            </label>
                                        </div>
                                    </div>

                                    <div class="flex space-x-3 mb-4 text-sm font-medium">
                                        <div class="flex-auto flex space-x-3">
                                            <button class="btn btn-sm btn-primary" type="submit">Update</button>
                                            <a href="{{route('categories.index')}}" class="btn btn-sm btn-danger" type="reset">Clear</a>
                                        </div>
                                    </div>
                                </form>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</x-app-layout>

resources/views/admin/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="container-fluid container_ p-4">

        <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-6 col-12">
                <div class="bg-white m-1 border rounded">
                    <div class="d-flex justify-content-between pt-2 pr-2 pl-2 border-bottom">
                        <p class="p-box">Today Users</p>
                        <p>{{$new_users->count()}}</p>
                    </div>
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" class="w-25" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                        </svg>
                    </div>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 col-sm-6 col-12">
                <div class="bg-white m-1 border rounded">
                    <div class="d-flex justify-content-between pt-2 pr-2 pl-2 border-bottom">
                        <p class="badge bg-warning text-white">{{$users->count()}}</p>
                        <p class="p-box">All Users</p>
                    </div>
                    <div class="text-warning">
                        <svg xmlns="http://www.w3.org/2000/svg" class="w-25" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
                        </svg>
                    </div>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 col-sm-6 col-12">
                <div class="bg-white border rounded text-primary m-1">
                    <div class="d-flex justify-content-between pt-2 pr-2 pl-2 border-bottom">
                        <p>Today Projects</p>
                        <p class="badge bg-primary text-white">{{$new_projects->count()}}</p>
                    </div>
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" class="w-25" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M8 13v-1m4 1v-3m4 3V8M8 21l4-4 4 4M3 4h18M4 4h16v12a1 1 0 01-1 1H5a1 1 0 01-1-1V4z" />
                        </svg>
                    </div>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 col-sm-6 col-12">
                <div class="bg-white border rounded text-primary m-1">
                    <div class="d-flex justify-content-between pt-2 pr-2 pl-2 border-bottom">
                        <p>All Projects</p>
                        <p class="badge bg-primary text-white">{{$projects->count()}}</p>
                    </div>
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" class="w-25" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M7 12l3-3 3 3 4-4M8 21l4-4 4 4M3 4h18M4 4h16v12a1 1 0 01-1 1H5a1 1 0 01-1-1V4z" />
                        </svg>
                    </div>
                </div>
            </div>

        </div>

        
        <div class="mt-3">
            <div class="row">

                <div class="col-lg-6">
                    <div class="bg-white m-1 border rounded" style="height: 300px;">
                        @include('charts.google-bar-chart')
                    </div>
                </div>

                <div class="col-lg-6">
                    <div class="bg-white m-1 border rounded">
                         @include('charts.google-pie-chart')
                    </div>
                </div>

            </div>
        </div>
    
        
    </div>
</x-app-layout>

resources/views/admin/project.blade.php
hello word

resources/views/admin/projects.blade.php
<x-app-layout>

    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Projects') }}
        </h2>
    </x-slot>


    @if(Session::has('success'))
        <div class="bg-teal-100 border-t-4 border-teal-500 rounded-b text-teal-900 px-4 py-3 shadow-md absolute" role="alert">
            <div class="flex items-center">
                <div class="py-1">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-16 w-16" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                </div>
                <div>
                    <p class="font-bold">Success</p>
                    <p class="text-sm">{{session('success')}}</p>
                </div>
            </div>
        </div>
    @endif

    <div class="container">

        <div class="content-header mt-2 mb-4 p-2">
            <div class="row">
                <div class="col-lg-6">
                    <p class="p-box">Projects</p>
                    <div class="buttons">
                        <button class="btn btn-primary bnt-sm">Create</button>
                        <button class="btn btn-sm bg-gray">Import</button>
                    </div>
                </div>
                <div class="col-lg-6"></div>
            </div>
        </div>

        <div class="bg-white">
            <table class="table table-sm bg-white border">
                <thead>
                    <tr>
                        <th class="">Project</th>
                        <th class="">Status</th>
                        <th class="">Owner</th>
                        <th class="">Members</th>
                        <th class="">Completion </th>
                        <th class=""></th>
                    </tr>
                </thead>

                <tbody class="divide-y">
                    @foreach($all_projects as $project)
                        <tr>
                            <td class="">
                                @if($project->image_url == 'N/A')
                                    <small class="h-12 w-12 font-thin text-xs text-blue-500 bg-white rounded-full border flex justify-center items-center ring-2 ring-white">
                                        no image
                                    </small>
                                @else
                                    <img src="{{Storage::url($project->image_url)}}" class="rounded border">
                                @endif
                                {{$project->name}}
                            </td>
                            <td class="">
                                <i class="fas fa-circle text-yellow-500 mr-2"></i>{{$project->status}}</td>
                            <td class="">
                                @foreach($all_users as $user)
                                    @if($user->id == $project->user_id)
                                        {{$user->name}}
                                    @endif
                                @endforeach
                            </td>
                                            
                            <td class="">
                                <div class="flex">
                                    <?php
                                        $assigned_users = DB::table('assign_users')
                                        ->join('users', 'assign_users.user_id', '=', 'users.id')
                                        ->where('project_id', '=', $project->id)
                                        ->select('users.*')->get();
                                    ?>
                                    @foreach($assigned_users as $user)
                                        <img src="{{Storage::url($user->avatar)}}" alt="..." class="w-6 h-6 rounded-full border-2 border-blueGray-50 shadow -ml-4">
                                    @endforeach
                                </div>
                            </td>

                            <td class="">
                                <div class="flex items-center">
                                    <span class="mr-2">60%</span>
                                    <div class="relative w-full">
                                        <div class="overflow-hidden h-2 text-xs flex rounded bg-white">
                                            <div style="width: 60%" class="shadow-none flex flex-col text-center whitespace-nowrap text-white justify-center bg-yellow-500">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>

        </div>
    </div>
</x-app-layout>

resources/views/admin/users.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Projects') }}
        </h2>
    </x-slot>



    <div class="container-fluid">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <section class="relative bg-blueGray-50">
                <div class="bg-white d-block pt-1 pl-2 rounded mt-2 border mb-2">
                    <h5>List users</h5>
                </div>
                <div class="w-100 ">
                    <table class="table table-sm bg-white rounded">
                        <thead>
                            <tr>
                                <th class="">Name</th>
                                <th class="">Email</th>
                                <th class="">Phone</th>
                                <th class="">Status</th>
                                <th class="">Role</th>
                                <th class="">Projects</th>
                                <th class=""></th>
                            </tr>
                        </thead>

                        <tbody class="divide-y">
                            @foreach($all_users as $user)
                                <tr>
                                    <td>
                                        @if($user->avatar == 'N/A')
                                            <small class="h-12 w-12 font-thin text-xs text-blue-500 bg-white rounded-full border flex justify-center items-center">
                                                no image
                                            </small>
                                        @else
                                            <img src="{{Storage::url($user->avatar)}}" class="h-12 w-12 bg-white rounded border" alt="...">
                                        @endif

                                        {{$user->name}} 
                                    </td>
                                            <td class="">
                                                {{$user->email}}
                                            </td>
                                            <td class="capitalize">
                                                {{$user->phone}}
                                            </td>
                                            <td class="">
                                                <i class="fas fa-circle text-yellow-500 mr-2"></i>{{$user->status}}</td>
                                            <td class="capitalize">
                                                {{$user->role}}
                                            </td>
                                            <td class="">
                                                10
                                            </td>
                                            <td>
                                                <a href="{{route('users.destroy', $user->id)}}" 
                                                    class="status bg-danger">Delete</a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </section>

        </div>
    </div>

</x-app-layout>