routes/web.php
<?php

use App\Http\Controllers\AdminHomeController;
use App\Http\Controllers\AssignUserController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin']], function () {
    // dashboard routes
    Route::resource('/', AdminHomeController::class)->name('*', 'dashboard');

    // projects routes
    Route::resource('/projects', ProjectController::class)->name('*', 'projects');

    // projects category routes
    Route::resource('/categories', CategoryController::class)->name('*', 'categories');

    // users routes
    Route::resource('/users', UserController::class)->name('*', 'users');

    // profile routes
    Route::get('/profile', function () {return view('welcome');})->name('Profile');
});

Route::group(['prefix' => '', 'middleware' => ['auth', 'user']], function () {

    // Route::get('/', function () {
    //     return view('user.dashboard');
    // })->middleware(['auth'])->name('dashboard');

    // dashboard routes
    Route::resource('/', HomeController::class)->name('*', 'dashboard');

    // user routes
    Route::resource('/user', UserController::class)->name('*', 'user');

    // projects routes
    Route::resource('/my/project', ProjectController::class)->name('*', 'project');

    // projects category routes
    Route::resource('/assign', AssignUserController::class)->middleware(['auth'])->name('*', 'assign');
});

require __DIR__ . '/auth.php';

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'avatar',
        'name',
        'email',
        'phone',
        'title',
        'role',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $all_users = User::where('id', '!=', Auth::id())->orderBy('updated_at', 'desc')->get();

        return view('admin.users', [
            'all_users' => $all_users,
            'title' => 'Users',
            'desc' => 'This is meta description for all Users',
        ]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user_form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'gender' => ['required', 'string', 'max:255'],
            'title' => ['required', 'string', 'max:255'],
            'role' => ['required', 'string', 'max:255'],
            'password' => ['required', 'confirmed'],
        ]);

        if ($request->hasFile('avatar')) {
            $avatar = Storage::disk('local')->put('avatars', $request->file('avatar'));
            $user = User::create([
                'avatar' => $avatar,
                'name' => $request->name,
                'email' => $request->email,
                'gender' => $request->gender,
                'phone' => $request->phone,
                'title' => $request->title,
                'role' => $request->role,
                'password' => Hash::make($request->password),
            ]);
        } else {
            $user = User::create([
                'avatar' => 'N/A',
                'name' => $request->name,
                'email' => $request->email,
                'gender' => $request->gender,
                'phone' => $request->phone,
                'title' => $request->title,
                'role' => $request->role,
                'password' => Hash::make($request->password),
            ]);
        }

        event(new Registered($user));

        Auth::login($user);

        return redirect('register')->with('success', 'user successfully created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $edit_user = User::findOrFail($id);

        return view('admin.user_form', [
            'edit_user' => $edit_user,
            'title' => ucfirst($edit_user->name),
            'desc' => 'This is meta description for User Edit',
        ]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255'],
            'gender' => ['required', 'string', 'max:255'],
            'title' => ['required', 'string', 'max:255'],
            'role' => ['required', 'string', 'max:255'],
        ]);

        if ($request->hasFile('avatar')) {
            $avatar = Storage::disk('local')->put('avatars', $request->file('avatar'));
            $user = User::findOrFail($id)->update([
                'avatar' => $avatar,
                'name' => $request->name,
                'email' => $request->email,
                'gender' => $request->gender,
                'phone' => $request->phone,
                'title' => $request->title,
                'role' => $request->role,
            ]);
        } else {
            $user = User::findOrFail($id)->update([
                'avatar' => 'N/A',
                'name' => $request->name,
                'email' => $request->email,
                'gender' => $request->gender,
                'phone' => $request->phone,
                'title' => $request->title,
                'role' => $request->role,
            ]);
        }

        event(new Registered($user));

// Auth::login($user);

        return redirect('register')->with('success', 'user successfully updated!');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $users = User::withTrashed()
            ->where('id', $id)
            ->get();
        redirect('admin/users');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/user/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="container-fluid container_ p-4">
        <div class="row">

            <div class="col-lg-7 bg-white border rounded" style="height:auto !important;">
                @include('charts.google-bar-chart')
            </div>

            <div class="col-lg-5">
                <section style="d-block overflow:auto; height: 400px;">
                    <ul class="p-2">
                       
                        <a href="{{route('project.create')}}" class="btn btn-primary btn-sm">  New project  </a>
                           
                        @foreach($my_projects as $project)
                            <li class=" ">
                                <a href="{{route('project.show', $project->id)}}" class="box__user {{ucfirst($project->status)}}">
                                    <div class="box__image">
                                        <img src="{{Storage::url($project->image_url)}}" alt="" />         
                                    </div>
                                    <div class="box__description">
                                        <p>  {{ucfirst($project->name)}}  </p>
                                        <p>  {{ucfirst($project->title)}} </p>
                                    </div>
                                        
                                       
                                    <div class="col-start-2 row-start-1 row-end-3 sm:mt-4 lg:mt-0 xl:mt-4">
                                        <dt class="sr-only">Users</dt>
                                        <dd x-for="user in project.users" class="flex justify-end sm:justify-start lg:justify-end xl:justify-start -space-x-1.5">
                                            <div class="flex -space-x-1">
                                                <?php
                                                    $assigned_users = DB::table('assign_users')
                                                        ->join('users', 'assign_users.user_id', '=', 'users.id')
                                                        ->where('project_id', '=', $project->id)
                                                        ->select('users.*')->get();
                                                ?>

                                                @foreach($assigned_users as $user)
                                                    <img 
                                                        class="inline-block h-6 w-6 rounded-full ring-2 ring-white" 
                                                        src="{{Storage::url($user->avatar)}}" alt=""
                                                    />
                                                @endforeach

                                            </div>
                                        </dd>
                                    </div>
                                    </dl>
                                </a>
                            </li>
                        @endforeach                      
                        </ul>
                    </section>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/user/projects.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Projects') }}
        </h2>
    </x-slot>


    <div class="p-2">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <section class="relative bg-blueGray-50">
                <div class="w-full mb-12">
                    <div class="relative flex flex-col min-w-0 break-words w-full mb-6 shadow-lg rounded  bg-blue-500 text-white">
                        <div class="bg-white">
                            <table class="table table-sm">
                                <thead>
                                    <tr>
                                        <th class="">Project</th>
                                        <th class="">Status</th>
                                        <th class="">Members</th>
                                        <th class="">Completion </th>
                                        <th class="">Modification</th>
                                    </tr>
                                </thead>

                                <tbody class="divide-y">
                                    @foreach($my_projects as $project)
                                        <tr>
                                            <td class="">
                                                @if($project->image_url == 'N/A')
                                                    <small class="rounded border">
                                                        no image
                                                    </small>
                                                @else
                                                    <img src="{{Storage::url($project->image_url)}}" class="rounded border" alt="...">
                                                @endif

                                                {{$project->name}} 
                                            </td>
                                            </td>
                                            <td class="">
                                                <i class="badge badge-success"></i>{{$project->status}}</td>
                                            <td class="">
                                                <div class="flex">
                                                <?php
                                                    $assigned_users = DB::table('assign_users')
                                                        ->join('users', 'assign_users.user_id', '=', 'users.id')
                                                        ->where('project_id', '=', $project->id)
                                                        ->select('users.*')->get();
                                                ?>

                                                @foreach($assigned_users as $user)
                                                    <img src="{{Storage::url($user->avatar)}}" alt="..." class="w-6 h-6 rounded-full border-2 border-blueGray-50 shadow -ml-4">
                                                @endforeach
                                                </div>
                                            </td>

                                            <td class="">
                                               60%
                                            </td>

                                            <td class="">
                                                <a href="{{route('project.edit', $project->id)}}" class="text-white bg-primary status">Edit</a>
                                                <a href="{{route('project.destroy', $project->id)}}" class="bg-danger text-white status">Delete</a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </section>

        </div>
    </div>
</x-app-layout>